// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTa2eU5bwQ_avhIgHNLWk3d53LQlppGg',
    appId: '1:217184069177:web:e73064fdc602f9f125cfe8',
    messagingSenderId: '217184069177',
    projectId: 'chatapp-f6349',
    authDomain: 'chatapp-f6349.firebaseapp.com',
    storageBucket: 'chatapp-f6349.appspot.com',
    measurementId: 'G-GZGSPL1G05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkW8z4YKn3Pa6Mv4uK3SJFoPMuA7DnhU',
    appId: '1:217184069177:android:cd3c15ba4c9a1feb25cfe8',
    messagingSenderId: '217184069177',
    projectId: 'chatapp-f6349',
    storageBucket: 'chatapp-f6349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEgHGy04AOoqVAHDZtL_eeKnpBiXKrIk',
    appId: '1:217184069177:ios:0547237a403bef4b25cfe8',
    messagingSenderId: '217184069177',
    projectId: 'chatapp-f6349',
    storageBucket: 'chatapp-f6349.appspot.com',
    iosBundleId: 'com.example.appMensagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEgHGy04AOoqVAHDZtL_eeKnpBiXKrIk',
    appId: '1:217184069177:ios:0547237a403bef4b25cfe8',
    messagingSenderId: '217184069177',
    projectId: 'chatapp-f6349',
    storageBucket: 'chatapp-f6349.appspot.com',
    iosBundleId: 'com.example.appMensagem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnTa2eU5bwQ_avhIgHNLWk3d53LQlppGg',
    appId: '1:217184069177:web:e3c7dd08ecadfe2c25cfe8',
    messagingSenderId: '217184069177',
    projectId: 'chatapp-f6349',
    authDomain: 'chatapp-f6349.firebaseapp.com',
    storageBucket: 'chatapp-f6349.appspot.com',
    measurementId: 'G-MLQRVED2N6',
  );
}
